<?xml version="1.0" encoding="utf-8"?><Database Name="CarCaptain Autospares" Class="dbTablesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;|DataDirectory|\CarCaptain Autospares.mdf&quot;;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CarCaptain_AutosparesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Invoice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Product" Member="Products" ThisKey="UserId" OtherKey="User_ID" Type="Product" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="UserId" OtherKey="UserId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="P_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImgLocation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_InvoiceProduct" Member="InvoiceProducts" ThisKey="P_Id" OtherKey="P_Id" Type="InvoiceProduct" />
      <Association Name="User_Product" Member="User" ThisKey="User_ID" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyingPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Invoice_InvoiceProduct" Member="InvoiceProducts" ThisKey="Invoice_ID" OtherKey="Invoice_ID" Type="InvoiceProduct" />
      <Association Name="User_Invoice" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceProduct" Member="InvoiceProducts">
    <Type Name="InvoiceProduct">
      <Column Name="InvoiceProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyingPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Invoice_InvoiceProduct" Member="Invoice" ThisKey="Invoice_ID" OtherKey="Invoice_ID" Type="Invoice" IsForeignKey="true" />
      <Association Name="Product_InvoiceProduct" Member="Product" ThisKey="P_Id" OtherKey="P_Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>